### ISSUE TITLE
downloading filters and them not loading 

### ISSUE THREAD

**Issue by REALtony4twenty** [ptrumpis/snap-camera-server-auto-config#1]
I am able to get the filters to appear on snap camera. I can favorite them. However, when I click on them to apply the filter. I get stuck in constantly loading the filter and it never changes.

**Comment by ptrumpis** [comment]
Sounds like you didn't apply the signature patch
https://github.com/ptrumpis/snap-camera-signature-patch

**Comment by REALtony4twenty** [comment]
I did. I made sure it was a match before I patched as well. Before I did that patch I wasnt even able to search for lenses from the website. So I know it took the patch.

**Comment by ptrumpis** [comment]
Searching lenses always works regardless of the patch, but trying to use them will lead to infinite loading if the patch is not applied.

- Open a new ticket at https://github.com/ptrumpis/snap-camera-server/issues
- And attach your log file `%USERPROFILE%\AppData\Local\Snap\Snap Camera\Log.txt`
